<?php

namespace Test\Core;

class UserTest extends \PHPUnit\Framework\TestCase
{
    protected $user;

    /*
     * Метод при загрузке
     * */
    protected function setUp(): void
    {
        $this->user = new User();

        $this->user->name = 'name';
    }

    public function testName()
    {
        $this->assertEquals('name', $this->user->name);
    }

    public function testGetHash()
    {

    }

    public function testAll()
    {

    }

    public function testCreate()
    {

    }

    /*
    * Метод после теста
    * */
    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}